<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<testResult type="org.overture.codegen.tests.exec.TracesVerdictJavaGenTest">
<result>
<output object="rO0ABXNyABBqYXZhLnV0aWwuVmVjdG9y2Zd9W4A7rwEDAANJABFjYXBhY2l0eUluY3JlbWVudEkADGVsZW1lbnRDb3VudFsAC2VsZW1lbnREYXRhdAATW0xqYXZhL2xhbmcvT2JqZWN0O3hwAAAAAAAAAAN1cgATW0xqYXZhLmxhbmcuT2JqZWN0O5DOWJ8QcylsAgAAeHAAAAAKc3IAKW9yZy5vdmVydHVyZS5jdC5jdHJ1bnRpbWUudXRpbHMuVHJhY2VUZXN0feFkkkPBXUACAARMAAJub3QAE0xqYXZhL2xhbmcvSW50ZWdlcjtMAAZyZXN1bHR0ABJMamF2YS9sYW5nL1N0cmluZztMAAR0ZXN0cQB+AAdMAAd2ZXJkaWN0dAApTG9yZy9vdmVydHVyZS9pbnRlcnByZXRlci90cmFjZXMvVmVyZGljdDt4cHNyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAAABdAABNHQABmEub3AoKX5yACdvcmcub3ZlcnR1cmUuaW50ZXJwcmV0ZXIudHJhY2VzLlZlcmRpY3QAAAAAAAAAABIAAHhyAA5qYXZhLmxhbmcuRW51bQAAAAAAAAAAEgAAeHB0AAZQQVNTRURzcQB+AAVzcQB+AAoAAAACdABFNCA7IEVycm9yIDQxMDU6IENhbid0IGdldCBvYmplY3QgdmFsdWUgb2YgbmlsIGluICdFbnRyeScgYXQgbGluZSAxNzo1dAAOYS5vcCgpOyBhLm9wKCl+cQB+AA90AAZGQUlMRURzcQB+AAVzcQB+AAoAAAADdAABNHQABmEub3AoKXEAfgARcHBwcHBwcHg=" resource="SameTestTwice.vdmpp" value="[TraceTest: Number: 1 Test: a.op() Result: 4 Verdict: PASSED, TraceTest: Number: 2 Test: a.op(); a.op() Result: 4 ; Error 4105: Can't get object value of nil in 'Entry' at line 17:5 Verdict: FAILED, TraceTest: Number: 3 Test: a.op() Result: 4 Verdict: PASSED]"/>
</result>
</testResult>
